### ISSUE TITLE
Need help in modifying ANSUSERSHARED.bat/ANSCUST.bat for version V195/Ansys 2019 R3 

### ISSUE THREAD

**Issue by PrasanthVemula** [dutitello/debug-ansys-upf#1]
Hey,

I`m trying to develop a new material model using usermat (in Ansys 2019 R3) for which I want to use visual studio 2017 as a debugger. 

I`m using ANSCUST.bat for compiling my usermat. 

I would be glad if you help me modify them for debugging. 

Also, it is not allowing me to attach .bat files. So, I`m attaching that content via .docs.

You can fwd me the modified files to ### REMOVED###.

[ANSUSERSHARED.docx](https://github.com/dutitello/debug-ansys-upf/files/6186913/ANSUSERSHARED.docx)
[ANSCUST.docx](https://github.com/dutitello/debug-ansys-upf/files/6186914/ANSCUST.docx)
[ANSUPF.docx](https://github.com/dutitello/debug-ansys-upf/files/6186915/ANSUPF.docx)

**Comment by dutitello** [comment]
Hi!

I've edited your `ANSUSERSHARED.bat` and `ANSCUST.bat` files, I'm uploading them [here at this same repo](https://github.com/dutitello/debug-ansys-upf/tree/master/bats). 

Since you're using `ANSCUST.bat` you also need an edited version of `ansys.lrf` for linking, I'm uploading one that I have from a previous version, it should work, but if not please send me your original file :). I renamed it as `ansys_v195.lrf` and changed it in the `ANSCUST.bat`, so it should work with this new name. 

I've committed the original and the edited version of these files, so you can see the differences [here](https://github.com/dutitello/debug-ansys-upf/commit/851dfec4325afc0f5b76d7a8d2396c3c0f1d7dc8?branch=851dfec4325afc0f5b76d7a8d2396c3c0f1d7dc8&diff=split) and [here](https://github.com/dutitello/debug-ansys-upf/commit/89b4145255a2547d231db2daad7ccbacb3d8ddd4?branch=89b4145255a2547d231db2daad7ccbacb3d8ddd4&diff=split). 

I hope it works.

**Comment by PrasanthVemula** [comment]
Hey,

Really thanks for helping me out.

I`ve tried the workflow that you`ve said. unfortunately, didn`t work for me. (I can attach in VS but APDL runs as if there is no debugger). I might be doing something wrong, So I`m attaching the procedure I`ve followed.

1. replaced the ANSCUST.BAT and ansys.lrf files with the one you`ve given.

![image](https://user-images.githubusercontent.com/43994335/112268756-76740080-8c9d-11eb-80af-a48feadf908e.png)

2. Copied usermat.F from examples to win64

![image](https://user-images.githubusercontent.com/43994335/112269108-f00bee80-8c9d-11eb-904f-a646ec681d5e.png)

3. compiling ANSCUST.BAT using intel compiler (I thought there might be an issue here; In the first image intel Fortran compiler 17 is written and I`m using intel one API Fortran compiler 2021)

![image](https://user-images.githubusercontent.com/43994335/112269356-45e09680-8c9e-11eb-9b2e-676872a21a44.png)
![image](https://user-images.githubusercontent.com/43994335/112269606-98ba4e00-8c9e-11eb-858e-cbfc103b7966.png)
![image](https://user-images.githubusercontent.com/43994335/112270209-5d6c4f00-8c9f-11eb-9624-592754dbffd1.png)

4. opened usermat in VS professional 2017 and custom executable in ansys APDL
![image](https://user-images.githubusercontent.com/43994335/112270610-e5eaef80-8c9f-11eb-87ef-c1ee607ee45c.png)
![image](https://user-images.githubusercontent.com/43994335/112270680-00bd6400-8ca0-11eb-8c58-13426135fc98.png)
![image](https://user-images.githubusercontent.com/43994335/112270810-29ddf480-8ca0-11eb-85f4-cd51521c33eb.png)
added breakpoints
![image](https://user-images.githubusercontent.com/43994335/112270902-42e6a580-8ca0-11eb-80ac-2d6eede6f0a0.png)

I`ve tried to run the Ansys BISO vs Usermat BISO in apdl. (attaching the .docx file as well)
![image](https://user-images.githubusercontent.com/43994335/112271162-9822b700-8ca0-11eb-815a-61571a2b89d9.png)

5. Ansys APDL generated results as if there is no debugger running in the background
![image](https://user-images.githubusercontent.com/43994335/112271538-0ff0e180-8ca1-11eb-8aad-f8b867c43ae5.png)

NOTE: does this issue has to with wrong intel compilers. in the manual, it was suggested to use " Intel Visual FORTRAN 17.0.6 compilers". As I said I`m using intel One API Fortran compiler 2021. I`ve tried changing the "IFORT_HOME" parameter in ANSCUST.BAT from "=%IFORT_COMPILER17%"" to =%IFORT_COMPILER21%". unfortunately the result is the same in every step.

[USER_BISO.docx](https://github.com/dutitello/debug-ansys-upf/files/6195181/USER_BISO.docx)

**Comment by dutitello** [comment]
The Intel One API Fortran compiler 2021 isn't a problem, I used some different Intel compilers with success (including 2021), if you start the compiler console by Windows start (as you did) it works well.

There are some important points that I'm not sure you did:

1) At the end of compilation, have you copied the runtime DLLS? 
![image](https://user-images.githubusercontent.com/34589867/112309380-0a37d380-8c82-11eb-8b4c-7ff40e517315.png)

.

2) Have you set the location of your custom `ansys.exe` file at Mechanical APDL Launcher before run?
![image](https://user-images.githubusercontent.com/34589867/112309649-55ea7d00-8c82-11eb-9a18-b070ae76a5df.png)

3) The `usermat.F` file opened in Visual Studio for debugging is located at the same directory of `ansys.exe` set before, at 2)? There is an `ANSYS.pdb` (this contain debug information) file in this directory?
![image](https://user-images.githubusercontent.com/34589867/112311394-6ac81000-8c84-11eb-9a4f-da61cfdee906.png)

**Comment by PrasanthVemula** [comment]
1. Yeah, I`ve copied the DLL's after the compilation
![image](https://user-images.githubusercontent.com/43994335/112320087-b4404b80-8cd4-11eb-940e-11bcf07ae512.png)

2. yeah I did and tried validation of that usermat as well.

3. I`ve used the same usermat.F file in the directory of the custom executable used in Ansys APDL. and all the files that were in the image were there as well.

Do you think I need to modify ANSUSERSHARED.bat file or any other file as well.

**Comment by dutitello** [comment]
I don't think that ANSUSERSHARED.bat need to be modified, since you are using a custom executable, but you can try. 

About the validation of usermat, this original script is pre-compiled inside ANSYS, so if there isn't an usermat compiled it still works. Something that usually helps to know if the correct script is running is to append some FORTRAN writes in the `usermat.F`, like ` WRITE(*,*) 'HI FROM USERMAT!'`, this will write at ANSYS Console while the code runs, could you try this?

**Comment by PrasanthVemula** [comment]
Yeah, seems like usermat is fine.

![image](https://user-images.githubusercontent.com/43994335/112422914-ad0e5180-8d57-11eb-9fd3-6b1478080069.png)

Do you think there are any custom file paths w.r.t. my pc or 2019 R3(v195), that I need to modify in ANSCUST.BAT.

**Comment by dutitello** [comment]
I don't think so, it shouldn't compile and link with incorrect paths in ANSCUST. 

Reviewing our conversation I've noted that your breakpoints are 'fully red' in [this image](https://user-images.githubusercontent.com/43994335/112270902-42e6a580-8ca0-11eb-80ac-2d6eede6f0a0.png), were this taken after the ANSYS was attached to Visual Studio Debugger? I ask you this because when you put breakpoints and attach to a software that it can't debug this will happen: 
![image](https://user-images.githubusercontent.com/34589867/112473619-5a2f9c80-8d4d-11eb-8fe8-c709078ea522.png)

BUT, when it can debug, this will happen:
![image](https://user-images.githubusercontent.com/34589867/112473938-bbf00680-8d4d-11eb-8bf2-bb9e784816a8.png)

If you're in the second case we are looking for the wrong problem and should focus in the Visual Studio.

**Comment by PrasanthVemula** [comment]
you`re right!!!!

just you know what I did...
1. opened your ".lrf", ".bat" file in raw format. saved them to my dir.

![image](https://user-images.githubusercontent.com/43994335/112598771-14e69a00-8e35-11eb-919c-8b6ddcf236c4.png)
![image](https://user-images.githubusercontent.com/43994335/112598781-17e18a80-8e35-11eb-97f3-dd3940ba1845.png)

after compiling...
2. opened usermat in VS
![image](https://user-images.githubusercontent.com/43994335/112599223-ac4bed00-8e35-11eb-80b0-2515b3095626.png)

3. attached custom exe.
![image](https://user-images.githubusercontent.com/43994335/112599262-b8d04580-8e35-11eb-99c7-652156dd295c.png)

![image](https://user-images.githubusercontent.com/43994335/112599288-c1c11700-8e35-11eb-9e5f-62aa9eda06c2.png)

4. I`ve attached the debugger
![image](https://user-images.githubusercontent.com/43994335/112599301-c5549e00-8e35-11eb-89b9-71b2e21617a9.png)
![image](https://user-images.githubusercontent.com/43994335/112599460-f6cd6980-8e35-11eb-8ea6-4a92cfc215c7.png)

**Comment by dutitello** [comment]
Ok, everything looks right.

I've changed some lines at `debug_anscust_v195.bat`, please download it again.

Can you send me the original `ansys.lrf` file? Or even better, open it and add a line with `-debug`, in the beginning of the file.

When you attach the debugger, in the output tab, does it says that symbols are loaded for your custom `ansys.exe`? Like here:

![image](https://user-images.githubusercontent.com/34589867/112626301-ca522700-8e0e-11eb-9ecb-c69d32e479d5.png)

You're using INTEL MPI for multithreads, try to change it to 'shared-memory parallel', I don't belive that it's the problem, but you can try.

![image](https://user-images.githubusercontent.com/34589867/112626869-94fa0900-8e0f-11eb-83a3-ec6b9ca730f8.png)

One more test that you can do is to copy ansys.lrf, debug_anscust_v195.bat, ansysex.def and app.manifest to another folder e try to run from there, maybe something changes....

**Comment by PrasanthVemula** [comment]
Hey,

Recompiled again with updated ANSCUST.BAT and added "-debug" in first line of "ansys.lrf". but still attaching my "ansys.lrf" for repo compatibility. It`s not allowing to attach ".lrf" file. so, attaching ".docx" format.

regarding symbols, it`s still the same error. But there were "Symbols loaded".
![image](https://user-images.githubusercontent.com/43994335/112721618-cf0bfd80-8f2a-11eb-9726-0fc9d73c5e49.png)

Tried to run compile in custom directory...
![image](https://user-images.githubusercontent.com/43994335/112722304-c3bad100-8f2e-11eb-8c16-0a6ac748f029.png)
![Untitled](https://user-images.githubusercontent.com/43994335/112722403-70954e00-8f2f-11eb-8cc2-a48eaa3a600f.png)

The symbols are showing correctly if I run in custom directory😲...
![image](https://user-images.githubusercontent.com/43994335/112722465-be11bb00-8f2f-11eb-962d-4b80f1b86802.png)

but when I try to run code in apdl command line "User_BISO.docx" attached above , Its going as if there is no debugger.


[ansys.docx](https://github.com/dutitello/debug-ansys-upf/files/6215640/ansys.docx)

**Comment by dutitello** [comment]
NICE!

Since you have 3 ANSYS icons in your task bar I believe you're using INTEL MPI, please change it to `Use Shared-Memory Parallel (SMP)` here: 
![img](https://user-images.githubusercontent.com/34589867/112626869-94fa0900-8e0f-11eb-83a3-ec6b9ca730f8.png)

If you're using MPI there is one `ansys.exe` process for each thread:
![image](https://user-images.githubusercontent.com/34589867/112724432-13c77280-8ef2-11eb-8be7-520d2a2184ca.png)

Testing here sometimes I needed to attach the debugger to one process, sometimes to other, it looks random... I can't know if it's my computer or what, but `SMP` looks better for debugging.

**Comment by PrasanthVemula** [comment]
It totally worked!!!!!

![image](https://user-images.githubusercontent.com/43994335/112727659-844dae00-8f49-11eb-9cfc-fc33cf84f424.png)

you`re a genius bro 🤩🤩🤩.

REALLY THANKS FOR HELPING AND SOLVING THE ISSUE EVEN IT TOOK QUITE SOME ITERATIONS.

**Comment by dutitello** [comment]
**AWESOME!**
Good luck with the usermat/UPFs! If you need something call me 😃 I've a good experience with usermat

It's just curiosity, but can I ask what are you working on?

**Comment by PrasanthVemula** [comment]
Indeed. Please ping me on v.n.v.prasanth@gmail.com.

**Comment by dutitello** [comment]
I sent an email to the address you posted in the begging of our conversation. I also hide it for you, I don't think it's a good ideia to keep it public here.
